# Generated by Django 4.2.4 on 2023-08-18 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_collection_featured_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='unit_price',
        ),
    ]
