# Generated by Django 4.2.4 on 2023-11-07 10:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0004_alter_customer_membership"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customer",
            options={
                "ordering": ["user__first_name", "user__last_name"],
                "permissions": [("view_history", "Can view history")],
            },
        ),
    ]
